openapi: "3.0.2"
info:
  title: Minecraft ABS - API
  version: "1.0"
servers:
  - url: https://localhost/api
paths:
  /api/register:
    post:
      tags:
        - Users
      summary: Registrasi user baru.
      description: Registrasi user baru.
      requestBody:
        required: true
        description: Berikut adalah data yang diperlukan pada request body untuk melakukan registrasi user baru.
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
                - email
                - phone
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
                phone:
                  type: string
            example:
              username: budi
              password: "rahasia"
              email: budi@example.xyz
              phone: "0812345678"

      responses:
        "201":
          description: Berhasil registrasi user.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: new user registered
        "409":
          description: Gagal registrasi user.
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
              examples:
                Gagal:
                  description: Gagal registrasi user baru.
                  value:
                    message:
                      - username already exist
                      - email already exist
                      - phone number already exist
  /api/login:
    post:
      tags:
        - Users
      summary: Login user.
      description: Login user.
      requestBody:
        required: true
        description: Berikut adalah data yang diperlukan pada request body untuk melakukan post login request
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                password:
                  type: string
            example:
              username: budi
              password: rahasia
      responses:
        "200":
          description: User berhasil login.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  username:
                    type: string
                  email:
                    type: string
                  phone:
                    type: string
                  email_verified_at:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
              example:
                message: login success
                data:
                  id: 1
                  username: budi
                  email: budi@example.xyz
                  phone: "0812345678"
                  email_verified_at: null
                  created_at: 2024-01-02 09:01:53
                  updated_at: 2024-01-02 09:01:53
        "401":
          description: User gagal login.
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string
              examples:
                Gagal login:
                  description: User gagal login.
                  value:
                    message: username or password invalid
